version: '3.1'

services:
  mycoloroflife:
    build:
      context: .
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
    restart: always