version: '3.8'

services:
  my-color-of-life-db:
    image: postgres:latest
    restart: always
    build:
      context: .
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - my-color-of-life-db:/var/lib/postgresql/data
volumes:
  my-color-of-life-db:
    driver: local