CREATE TABLE t_activation_code
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(15)                              NOT NULL,
    user_id         INTEGER,
    course_title_id INTEGER,
    CONSTRAINT pk_t_activation_code PRIMARY KEY (id)
);

CREATE TABLE t_course_progress
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id INTEGER,
    user_id   INTEGER,
    CONSTRAINT pk_t_course_progress PRIMARY KEY (id)
);

CREATE TABLE t_course_title
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_t_course_title PRIMARY KEY (id)
);

ALTER TABLE t_course
    ADD course_title_id INTEGER;

ALTER TABLE t_course
    ALTER COLUMN course_title_id SET NOT NULL;

ALTER TABLE t_activation_code
    ADD CONSTRAINT FK_T_ACTIVATION_CODE_ON_COURSE_TITLE FOREIGN KEY (course_title_id) REFERENCES t_course_title (id);

ALTER TABLE t_activation_code
    ADD CONSTRAINT FK_T_ACTIVATION_CODE_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

ALTER TABLE t_course
    ADD CONSTRAINT FK_T_COURSE_ON_COURSE_TITLE FOREIGN KEY (course_title_id) REFERENCES t_course_title (id);

ALTER TABLE t_course_progress
    ADD CONSTRAINT FK_T_COURSE_PROGRESS_ON_COURSE FOREIGN KEY (course_id) REFERENCES t_course (id);

ALTER TABLE t_course_progress
    ADD CONSTRAINT FK_T_COURSE_PROGRESS_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

ALTER TABLE t_course
    DROP COLUMN course_title;

ALTER TABLE t_course
    ALTER COLUMN text TYPE VARCHAR(255) USING (text::VARCHAR(255));