CREATE TABLE t_role
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_t_role PRIMARY KEY (id)
);

CREATE TABLE t_user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255),
    CONSTRAINT pk_t_user PRIMARY KEY (id)
);

CREATE TABLE t_user_roles
(
    roles_id  INTEGER NOT NULL,
    t_user_id INTEGER NOT NULL,
    CONSTRAINT pk_t_user_roles PRIMARY KEY (roles_id, t_user_id)
);

ALTER TABLE t_user_roles
    ADD CONSTRAINT fk_tuserol_on_role FOREIGN KEY (roles_id) REFERENCES t_role (id);

ALTER TABLE t_user_roles
    ADD CONSTRAINT fk_tuserol_on_user FOREIGN KEY (t_user_id) REFERENCES t_user (id);