CREATE TABLE t_article
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time_of_creation VARCHAR(16)                              NOT NULL,
    title                 VARCHAR(100)                             NOT NULL,
    text                  TEXT                                     NOT NULL,
    CONSTRAINT pk_t_article PRIMARY KEY (id)
);

CREATE TABLE t_article_users
(
    t_article_id INTEGER NOT NULL,
    users_id     INTEGER NOT NULL,
    CONSTRAINT pk_t_user_articles PRIMARY KEY (t_article_id, users_id)
);

ALTER TABLE t_article_users
    ADD CONSTRAINT fk_tuseart_on_article FOREIGN KEY (t_article_id) REFERENCES t_article (id);

ALTER TABLE t_article_users
    ADD CONSTRAINT fk_tuseart_on_user FOREIGN KEY (users_id) REFERENCES t_user (id);