CREATE TABLE t_event
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time_of_creation VARCHAR(16),
    title                 VARCHAR(100)                             NOT NULL,
    text                  TEXT                                     NOT NULL,
    CONSTRAINT pk_t_event PRIMARY KEY (id)
);

CREATE TABLE t_event_users
(
    t_event_id INTEGER NOT NULL,
    users_id   INTEGER NOT NULL,
    CONSTRAINT pk_t_event_users PRIMARY KEY (t_event_id, users_id)
);

ALTER TABLE t_event_users
    ADD CONSTRAINT fk_teveuse_on_event FOREIGN KEY (t_event_id) REFERENCES t_event (id);

ALTER TABLE t_event_users
    ADD CONSTRAINT fk_teveuse_on_user FOREIGN KEY (users_id) REFERENCES t_user (id);

ALTER TABLE t_article
    ALTER COLUMN date_time_of_creation DROP NOT NULL;