CREATE TABLE t_course
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_title VARCHAR(100)                             NOT NULL,
    page         INTEGER                                  NOT NULL,
    video_title  VARCHAR(100),
    video_link   VARCHAR(255),
    text         TEXT,
    CONSTRAINT pk_t_course PRIMARY KEY (id)
);