CREATE TABLE t_secure_token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255),
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    expire_at  TIMESTAMP WITHOUT TIME ZONE,
    user_id    INTEGER,
    CONSTRAINT pk_t_secure_token PRIMARY KEY (id)
);

ALTER TABLE t_user
    ADD is_account_non_locked BOOLEAN;

ALTER TABLE t_user
    ALTER COLUMN is_account_non_locked SET NOT NULL;

ALTER TABLE t_secure_token
    ADD CONSTRAINT uc_t_secure_token_token UNIQUE (token);

ALTER TABLE t_secure_token
    ADD CONSTRAINT FK_T_SECURE_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);